spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:delivery;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;TIME ZONE=UTC
  jpa:
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
  activemq:
    pool:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5670

  cloud:
    stream:
      bindings:
        output:
          destination: delivery-created
        deliveryCreated:
          destination: delivery-created
          group: delivery
        adjustmentModified:
          destination: adjustment-modified
          group: delivery
        bonusModified:
          destination: bonus-modified
          group: delivery



